version: '3'
services:
  database:
    image: postgres:alpine
    ports:
      - "5436:5432"
    networks:
      - itmo-network
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  backend:
    build:
      context: backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      UPLOAD_DIR: ${UPLOAD_DIR}
    volumes:
      - ../static:/app/static
      - ./backend/logs:/app/logs/

    networks:
      - itmo-network
  frontend:
    build:
      context: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ../static:/usr/share/nginx/html/static
    networks:
      - itmo-network
networks:
  itmo-network:
