version: '3'
services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - itmo-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      UPLOAD_DIR: ${UPLOAD_DIR}
    volumes:
      - ../static:${UPLOAD_DIR}
      - ./logs:/app/logs/

    networks:
      - itmo-network

networks:
  itmo-network:
