spring:
  application:
    name: feedback-itmo
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database
    username: postgres
    password: new_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
accessTokenSecret: testAccessTokenSecret
refreshTokenSecret: testRefreshTokenSecret
accessTokenExpirationMinutes: 60
refreshTokenExpirationDays: 2
upload-dir: src/main/resources/static