spring:
  application:
    name: feedback-itmo
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
accessTokenSecret: testAccessTokenSecret
refreshTokenSecret: testRefreshTokenSecret
accessTokenExpirationMinutes: 60
refreshTokenExpirationDays: 2
upload-dir: ${UPLOAD_DIR}